[package]
name = "rsqlt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
rusqlite = "0.36.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_rusqlite = "0.39.0"
toml = "0.8.23"
